version: "3.8"

services:
  quotation:
    build:
      context: .
      args:
        SERVICE_NAME: quotation
    ports:
      - "8081:8081"

  risk:
    build:
      context: .
      args:
        SERVICE_NAME: risk
    ports:
      - "8082:8082"

  purchase:
    build:
      context: .
      args:
        SERVICE_NAME: trade
    ports:
      - "8083:8083"
